export const culturaOptions = [
    "Algodão",
    "Amendoim",
    "Amendoim forrageiro (pastagem)",
    "Amendoim forrageiro (cobertura solo)",
    "Andropogon (pastagem)",
    "Andropogon (cobertura do solo)",
    "Azevém (pastagem)",
    "Azevém (cobertura do solo)",
    "Arroz terras altas (grão)",
    "Arroz terras baixas (inundado) (grão)",
    "Aveia branca (grão)",
    "Aveia branca (silagem/feno)",
    "Aveia branca (pastagem)",
    "Aveia branca (cobertura do solo)",
    "Aveia preta (grão)",
    "Aveia preta (silagem/feno)",
    "Aveia preta (pastagem)",
    "Aveia preta (cobertura do solo)",
    "Aveia amarela (grão)",
    "Aveia amarela (silagem/feno)",
    "Aveia amarela (pastagem)",
    "Aveia amarela (cobertura do solo)",
    "Brachiaria brizantha (pastagem)",
    "Brachiaria brizantha (cobertura do solo)",
    "Brachiaria decumbens (pastagem)",
    "Brachiaria decumbens (cobertura do solo)",
    "Brachiaria humidicola (pastagem)",
    "Brachiaria humidicola (cobertura do solo)",
    "Brachiaria ruziziensis (pastagem)",
    "Brachiaria ruziziensis (cobertura do solo)",
    "Canola (grão)",
    "Capim sudão (pastagem)",
    "Capim sudão (cobertura do solo)",
    "Capim Elefante (pastagem)",
    "Capim Elefante (cobertura do solo)",
    "Centeio (grão)",
    "Centeio (silagem/feno)",
    "Centeio (pastagem)",
    "Centeio (cobertura do solo)",
    "Cevada (grão)",
    "Cevada (silagem/feno)",
    "Cevada (pastagem)",
    "Cevada (cobertura do solo)",
    "Cornichão (silagem/feno)",
    "Cornichão (pastagem)",
    "Cornichão (cobertura do solo)",
    "Crotalária(s) (silagem/feno)",
    "Crotalária(s) (silagem/feno)",
    "Crotalária(s) (silagem/feno)",
    "Ervilha",
    "Ervilhaca (silagem/feno)",
    "Ervilhaca (pastagem)",
    "Ervilhaca (cobertura do solo)",
    "Estilosantes (silagem/feno)",
    "Estilosantes (pastagem)",
    "Estilosantes (cobertura do solo)",
    "Feijão (grão)",
    "Feijão caupi (grão)",
    "Feijão guandu (silagem/feno)",
    "Feijão guandu (pastagem)",
    "Feijão guandu (cobertura do solo)",
    "Gergelim (grão)",
    "Girassol (grão)",
    "Girassol (silagem/feno)",
    "Girassol (cobertura do solo)",
    "Grão de Bico (grão)",
    "Mamona (grão)",
    "Mandioca",
    "Milheto (grão)",
    "Milheto (silagem/feno)",
    "Milheto (pastagem)",
    "Milheto (cobertura do solo)",
    "Milho (grão)",
    "Milho (silagem/feno)",
    "Mucuna(s) (cobertura do solo)",
    "Panicum maximum (silagem/feno)",
    "Panicum maximum (pastagem)",
    "Panicum maximum (cobertura do solo)",
    "Soja (grão)",
    "Sorgo (grão)",
    "Sorgo (silagem/feno)",
    "Sorgo (pastagem)",
    "Sorgo (cobertura do solo)",
    "Tremoço branco (cobertura do solo)",
    "Trevo (silagem/feno)",
    "Trevo (pastagem)",
    "Trevo (cobertura do solo)",
    "Trigo (grão)",
    "Trigo (silagem/feno)",
    "Trigo (pastagem)",
    "Trigo (cobertura do solo)",
    "Triticale (grão)",
    "Triticale (silagem/feno)",
    "Triticale (pastagem)",
    "Triticale (cobertura do solo)"
]