export const modeloAnaliseSolo = () => {
  return {
    cpfResponsavelColeta: "",
    dataColeta: "",
    pontoColeta: "",
    camada: "20",
    areia: "",
    silte: "",
    argila: "",
    calcio: "",
    magnesio: "",
    potassio: "",
    sodio: "",
    aluminio: "",
    acidezPotencial: "",
    phh2o: "",
    phcaci: "",
    fosforoMehlich: "",
    fosforoResina: "",
    enxofre: "",
    mos: "",
    arilsulfatase: "",
    betaGlicosedade: "",
    densidadeSolo: "",
  };
};
